version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "furo"
          - "giturlparse"
          - "markdown-it-py"
          - "mdformat"
          - "mdformat-gfm"
          - "mdformat_footnote"
          - "mdformat_gfm_alerts"
          - "packaging"
          - "pyright"
          - "pytest-cov"
          - "pytest-regressions"
          - "pytest"
          - "PyYAML"
          - "semver"
          - "sphinx_design"
          - "sphinx-autobuild"
          - "sybil"
          - "tox"
          - "tox-uv"
          - "yuio"
      style:
        patterns:
          - "prek"
          - "ruff"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"
