name: Changelog Keeper action
description: Parse changelog and extract notes for a release.
author: Tamika Nomara

branding:
  icon: heart
  color: red

inputs:
  config:
    description: Path to the config file, relative to repository root.
    required: true
    default: ""
  changelog:
    description: Path to the changelog file, relative to repository root.
    required: true
    default: ""
  version:
    description: Version to search for, default is "latest".
    required: true
    default: "latest"
  strict:
    description: Run changelog keeper in strict mode.
    required: true
    default: "false"
  ignore-errors:
    description: Ignore issues found in changelog.
    required: true
    default: "false"

outputs:
  text:
    description: Extracted markdown text.
    value: ${{ fromJSON(steps.run-clk.outputs.data).text }}
  is-latest:
    description: Indicates that this is the latest release so far.
    value: ${{ fromJSON(steps.run-clk.outputs.data).isLatest }}
  is-pre-release:
    description: Indicates that this is a pre-release.
    value: ${{ fromJSON(steps.run-clk.outputs.data).isPreRelease }}
  is-post-release:
    description: Indicates that this is a post-release.
    value: ${{ fromJSON(steps.run-clk.outputs.data).isPostRelease }}
  is-unreleased:
    description: Indicates that action returned an unreleased section of changelog.
    value: ${{ fromJSON(steps.run-clk.outputs.data).isUnreleased }}
  data:
    description: Full JSON output of the "clk find" command.
    value: ${{ steps.run-clk.outputs.data }}

runs:
  using: composite
  steps:
    - name: Prepare pip cache key
      id: cache-key
      shell: sh
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
        echo "date=$(date --utc '+%Y-%m')" >> $GITHUB_OUTPUT
        echo "packages_hash=$(cat ${{ github.action_path }}/pyproject.toml | sha256sum | cut -f 1 -d ' ')" >> $GITHUB_OUTPUT
    - name: Restore pip cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.cache-key.outputs.dir }}
        key: cl-keeper-${{ runner.os }}-${{ steps.cache-key.outputs.packages_hash }}-${{ steps.cache-key.outputs.date }}
        restore-keys: |
          cl-keeper-${{ runner.os }}-${{ steps.cache-key.outputs.packages_hash }}-
          cl-keeper-${{ runner.os }}-
    - name: Install dependencies
      shell: sh
      run: |
        pipx install ${{ github.action_path }}
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION_FOR_CL_KEEPER: "0+action-${{ github.action_ref }}"
    - name: Save pip cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.cache-key.outputs.dir }}
        key: ${{ steps.cache.outputs.cache-primary-key }}
    - name: Run Changelog Keeper
      id: run-clk
      shell: bash
      run: |
        echo 'data<<EOF' >> $GITHUB_OUTPUT
        clk find ${{ inputs.version }} --json $FLAG_CONFIG $FLAG_CHANGELOG $FLAG_STRICT $FLAG_IGNORE_ERRORS | tee /dev/stderr >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      env:
        FLAG_CONFIG: ${{ inputs.config != '' && format('-c {0}', inputs.config) || '' }}
        FLAG_CHANGELOG: ${{ inputs.changelog != '' && format('-i {0}', inputs.changelog) || '' }}
        FLAG_STRICT: ${{ fromJSON(inputs.strict) && '--strict' || '' }}
        FLAG_IGNORE_ERRORS: ${{ fromJSON(inputs.ignore-errors) && '--ignore-errors' || '' }}
