name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Runs main tests for the package.
  test:
    name: Test package
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        type:
          - test
        include:
          - os: ubuntu-latest
            python-version: "3.13"
            type: code style
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install UV
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv tool install poethepoet
      # Tests
      - name: Test package
        if: ${{ matrix.type == 'test' }}
        run: |
          poe ci
      # Lint
      - name: Check code style
        if: ${{ matrix.type == 'code style' }}
        run: |
          poe lint --color always

  # Tests the cl-keeper GitHub Action itself.
  test-action:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run action
        id: action
        uses: ./
      - name: Print results
        env:
          TEXT: ${{ steps.action.outputs.text }}
          IS_LATEST: ${{ steps.action.outputs.is-latest }}
          IS_PRE_RELEASE: ${{ steps.action.outputs.is-pre-release }}
          IS_POST_RELEASE: ${{ steps.action.outputs.is-post-release }}
          IS_UNRELEASED: ${{ steps.action.outputs.is-unreleased }}
          DATA: ${{ steps.action.outputs.data }}
        run: |
          echo "text=$TEXT"
          echo "is-latest=$IS_LATEST"
          echo "is-pre-release=$IS_PRE_RELEASE"
          echo "is-post-release=$IS_POST_RELEASE"
          echo "is-unreleased=$IS_UNRELEASED"
          echo "data=$DATA"
