name: Test action
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  # Try running the action in this repo.
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run action
        id: action
        uses: ./
      - name: Print results
        run: |
          echo 'text=${{ steps.action.outputs.text }}'
          echo 'is-latest=${{ steps.action.outputs.is-latest }}'
          echo 'is-pre-release=${{ steps.action.outputs.is-pre-release }}'
          echo 'is-post-release=${{ steps.action.outputs.is-post-release }}'
          echo 'is-unreleased=${{ steps.action.outputs.is-unreleased }}'
          echo 'data=${{ steps.action.outputs.data }}'
